import 'package:flutter/material.dart';
import 'package:mica/src/providers/mica_provider.dart';

/// Utility class to help with transitioning from direct parameter passing to Provider pattern
class MicaStateInitializer {
  /// Initialize the MicaScoreModel with data from the TestSummary widget parameters
  static void initializeFromTestParameters({
    required BuildContext context,
    required String patientName,
    required String assessorName,
    required String handedness,
    required DateTime assessmentDate,
    required int languageComprehensionRadioValue,
    required int trialOneScore,
    required int trialTwoScore,
    required int trialThreeScore,
    required int visuospatialPraxisImage1,
    required int visuospatialPraxisImage2,
    required int visuospatialPraxisImage3,
    required int attention,
    required int attentionCorrect,
    required int attentionMistakes,
    required int executiveAnimalNaming,
    required int executiveAnimalNamingCount,
    required int executiveLexicalFluency,
    required int executiveLexicalFluencyCount,
    required int executiveDesignFluency,
    required int executiveFingerNose,
    required int executiveTap,
    required int executiveAlternatingSequences,
    required int executiveLuria,
    required int executiveLuriaScore,
    required int executiveSerial,
    required int executiveSerialScore,
    required int shorttermMemoryVerbal,
    required int shorttermMemoryVerbalScore,
    required int praxisRight,
    required int praxisLeft,
    required int tenWordDelay,
    required int scoreVerbalRecognitionMemoryTenWords,
    required int scoreVerbalRecognitionMemoryTenWordsInList,
    required int scoreVerbalRecognitionMemoryTenWordsNotInList,
    required int shorttermMemoryVisualImage1,
    required int shorttermMemoryVisualImage2,
    required int shorttermMemoryVisualImage3,
    required int anomiaAgnosia,
    required int agnosia,
    required int executive,
    required int spokenLanguage,
    // Gnosis parameters
    required int gnosisFingerPerceptionPattern1,
    required int gnosisFingerPerceptionPattern2,
    required int gnosisFingerPerceptionPattern3,
    required int gnosisFingerPerceptionPattern4,
    required int gnosisFingerPerceptionPattern5,
    required int gnosisFingerPerceptionPattern6,
    required int gnosisFingerPerceptionPattern7,
    required int gnosisFingerPerceptionTotal,
    required int gnosisVisualNominalDysphasia,
    required int gnosisVisualAgnosia,
    required int gnosisAstereognosisRight,
    required int gnosisAstereognosisLeft,
    required int gnosisClockDrawing,
    // Language parameters
    required int languageReading,
    required int languageRepetition,
    required int languageComprehensionMoving,
    required int languageWriting,
    required int languageObjectNaming,
    required int languageSpontaneousSpeech,
    required int languageComprehensionThreeStage,
    required int languagePictureNamingCorrect,
    required int languagePictureNamingTotal,
    required int languagePictureAgnosia,
    // Memory parameters
    required int memorySemanticScore,
    required int memoryVisualWorkingImage1,
    required int memoryVisualWorkingImage2,
    required int memoryVisualWorkingImage3,
    required int memoryShortVerbalCorrect,
    required int memoryShortVerbalTotal,
    required int memoryTenWordRecognitionCorrect,
    required int memoryTenWordRecognitionFalsePositive,
  }) {
    // Get the model without listening to changes
    final model = MicaProviders.getScoreModel(context, listen: false);

    // Initialize the model with the provided parameters
    model.initFromTestSummary(
      patientName: patientName,
      assessorName: assessorName,
      handedness: handedness,
      assessmentDate: assessmentDate,
      languageComprehensionRadioValue: languageComprehensionRadioValue,
      trialOneScore: trialOneScore,
      trialTwoScore: trialTwoScore,
      trialThreeScore: trialThreeScore,
      visuospatialPraxisImage1: visuospatialPraxisImage1,
      visuospatialPraxisImage2: visuospatialPraxisImage2,
      visuospatialPraxisImage3: visuospatialPraxisImage3,
      attention: attention,
      attentionCorrect: attentionCorrect,
      attentionMistakes: attentionMistakes,
      executiveAnimalNaming: executiveAnimalNaming,
      executiveAnimalNamingCount: executiveAnimalNamingCount,
      executiveLexicalFluency: executiveLexicalFluency,
      executiveLexicalFluencyCount: executiveLexicalFluencyCount,
      executiveDesignFluency: executiveDesignFluency,
      executiveFingerNose: executiveFingerNose,
      executiveTap: executiveTap,
      executiveAlternatingSequences: executiveAlternatingSequences,
      executiveLuria: executiveLuria,
      executiveLuriaScore: executiveLuriaScore,
      executiveSerial: executiveSerial,
      executiveSerialScore: executiveSerialScore,
      shorttermMemoryVerbal: shorttermMemoryVerbal,
      shorttermMemoryVerbalScore: shorttermMemoryVerbalScore,
      praxisRight: praxisRight,
      praxisLeft: praxisLeft,
      tenWordDelay: tenWordDelay,
      scoreVerbalRecognitionMemoryTenWords:
          scoreVerbalRecognitionMemoryTenWords,
      scoreVerbalRecognitionMemoryTenWordsInList:
          scoreVerbalRecognitionMemoryTenWordsInList,
      scoreVerbalRecognitionMemoryTenWordsNotInList:
          scoreVerbalRecognitionMemoryTenWordsNotInList,
      shorttermMemoryVisualImage1: shorttermMemoryVisualImage1,
      shorttermMemoryVisualImage2: shorttermMemoryVisualImage2,
      shorttermMemoryVisualImage3: shorttermMemoryVisualImage3,
      anomiaAgnosia: anomiaAgnosia,
      agnosia: agnosia,
      executive: executive,
      spokenLanguage: spokenLanguage,
      // Gnosis parameters
      gnosisFingerPerceptionPattern1: gnosisFingerPerceptionPattern1,
      gnosisFingerPerceptionPattern2: gnosisFingerPerceptionPattern2,
      gnosisFingerPerceptionPattern3: gnosisFingerPerceptionPattern3,
      gnosisFingerPerceptionPattern4: gnosisFingerPerceptionPattern4,
      gnosisFingerPerceptionPattern5: gnosisFingerPerceptionPattern5,
      gnosisFingerPerceptionPattern6: gnosisFingerPerceptionPattern6,
      gnosisFingerPerceptionPattern7: gnosisFingerPerceptionPattern7,
      gnosisFingerPerceptionTotal: gnosisFingerPerceptionTotal,
      gnosisVisualNominalDysphasia: gnosisVisualNominalDysphasia,
      gnosisVisualAgnosia: gnosisVisualAgnosia,
      gnosisAstereognosisRight: gnosisAstereognosisRight,
      gnosisAstereognosisLeft: gnosisAstereognosisLeft,
      gnosisClockDrawing: gnosisClockDrawing,
      // Language parameters
      languageReading: languageReading,
      languageRepetition: languageRepetition,
      languageComprehensionMoving: languageComprehensionMoving,
      languageWriting: languageWriting,
      languageObjectNaming: languageObjectNaming,
      languageSpontaneousSpeech: languageSpontaneousSpeech,
      languageComprehensionThreeStage: languageComprehensionThreeStage,
      languagePictureNamingCorrect: languagePictureNamingCorrect,
      languagePictureNamingTotal: languagePictureNamingTotal,
      languagePictureAgnosia: languagePictureAgnosia,
      // Memory parameters
      memorySemanticScore: memorySemanticScore,
      memoryVisualWorkingImage1: memoryVisualWorkingImage1,
      memoryVisualWorkingImage2: memoryVisualWorkingImage2,
      memoryVisualWorkingImage3: memoryVisualWorkingImage3,
      memoryShortVerbalCorrect: memoryShortVerbalCorrect,
      memoryShortVerbalTotal: memoryShortVerbalTotal,
      memoryTenWordRecognitionCorrect: memoryTenWordRecognitionCorrect,
      memoryTenWordRecognitionFalsePositive: memoryTenWordRecognitionFalsePositive,
    );
  }
}
